parameters:
  pool: ''

jobs:
- job: macos
  pool: ${{ parameters.pool }}

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '2.2.0'

  - task: nventiveCanaryUpdater@5
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries')
    inputs:
      solution: 'XamlControlsGallery.Windows/XamlControlsGallery.sln'
      usePrivateFeed: false
      useNuGetOrg: true
      mergeBranch: true
      branchToMerge: 'master'
      nugetUpdaterVersion: '2.0.2'
      allowDowngrade: true
      packageAuthor: 'nventive'
      summaryFile: '$(Build.ArtifactStagingDirectory)/Canary.md'
      resultFile: '$(Build.ArtifactStagingDirectory)/update_result.json'

  - bash: |
      shopt -s nullglob
      function join_by { local IFS="$1"; shift; echo "$*"; }
      lib_path=$(join_by ';' $(Agent.WorkFolder)/_tasks/GitVersion*/4.0.*/lib/linux/x86_64)
      echo LD_LIBRARY_PATH: $lib_path
      echo "##vso[task.setvariable variable=LD_LIBRARY_PATH]$lib_path"

    displayName: Update LD_LIBRARY_PATH for GitVersion
    
  - task: GitVersion@5
    # Ignore gitversion for forks, until this is fixed:
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      updateAssemblyInfo: false

  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple certificate'
    inputs:
      certSecureFile: '$(iOSSigning.Certificate)'
      certPwd: '$(iOSSigning.CertificatePwd)'
      signingIdentity: '$(iOSSigning.CertificateIdentity)'

  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install an Apple provisioning profile'
    inputs:
      provProfileSecureFile: '$(iOSSigning.ProvisioningProfile)'

  - task: MSBuild@1
    inputs:
      solution: build/Build.csproj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: "/r"
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
      
  - task: MSBuild@1
    inputs:
      solution: '$(build.sourcesdirectory)/XamlControlsGallery.iOS/XamlControlsGallery.iOS.csproj'
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release /p:Platform=iPhone /detailedsummary /m:16 /nr:false  "/p:PackageVersion=%GITVERSION_FullSemVer%" "/p:InformationalVersion=%GITVERSION_InformationalVersion%"
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: true
      createLogFile: true

  - task: CopyFiles@2
    displayName: 'Publish iOS Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/XamlControlsGallery.iOS/bin/iPhone/Release
      Contents: '*.ipa'
      TargetFolder: $(build.artifactstagingdirectory)/XamlUIBasics-iOS
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: universal-samples-drop
      ArtifactType: Container
